#!/usr/bin/python

# Generate vectors.S, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print("# generated by vectors.py - do not edit")
print("# interrupt service routines")
print(".global alltraps")
for i in range(256):
    print(f".global vector{i}")
    print(f"vector{i}:")
    if not (i == 8 or 10 <= i <= 14 or i == 17): # processor pushes error code instead
        print("  pushl $0")
    print(f"  pushl ${i}") # trap number
    print( "  jmp alltraps")

print()
print("# vector table")
print(".data")
print(".global vectors")
print("vectors:")
for i in range(256):
    print(f"  .quad vector{i}")

# sample output:
#   # interrupt service routines
#   .global alltraps
#   .global vector0
#   vector0:
#     pushl $0
#     pushl $0
#     jmp alltraps
#   ...
#   
#   # vector table
#   .data
#   .global vectors
#   vectors:
#     .long vector0
#     .long vector1
#     .long vector2
#   ...
